# Generated by Django 5.2.7 on 2025-10-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('WOOD', 'Wood'), ('METAL', 'Metal'), ('GLASS', 'Glass'), ('PLASTIC', 'Plastic'), ('FABRIC', 'Fabric'), ('LEATHER', 'Leather'), ('MARBLE', 'Marble'), ('BAMBOO', 'Bamboo'), ('PLYWOOD', 'Plywood'), ('MDF', 'Medium-Density Fiberboard'), ('RATTAN', 'Rattan / Wicker'), ('STONE', 'Stone'), ('ACRYLIC', 'Acrylic'), ('COMPOSITE', 'Composite / Engineered Material')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
