# Generated by Django 5.2.7 on 2025-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
